from typing import Any, List, Mapping, Optional, Protocol, runtime_checkable

from thorlabs_xa.shared.enums import TLMC_AnalogMonitorNumber, TLMC_AuxIoPortMode, TLMC_AuxIoPortNumber, TLMC_BowIndex, TLMC_CalibrationState, TLMC_CurrentLoopScenario, TLMC_DigitalInput, TLMC_DigitalOutput, TLMC_EnableState, TLMC_EndOfMoveMessagesMode, TLMC_IoPortNumber, TLMC_IoPositionTriggerEnableState, TLMC_KcubeMmiLockState, TLMC_MoveDirection, TLMC_MoveMode, TLMC_OperatingMode, TLMC_PZ_PositionControlMode, TLMC_PZ_SetNanoTrakModeType, TLMC_PZ_StatusBit, TLMC_ParameterGroupId, TLMC_PositionLoopScenario, TLMC_RackBayNumber, TLMC_RackBayOccupiedState, TLMC_ScaleType, TLMC_SettingStringFormat, TLMC_StatusItemId, TLMC_StopMode, TLMC_Unit, TLMC_UniversalStatusBit
from thorlabs_xa.shared.params import TLMC_AdcInputs, TLMC_AnalogMonitorConfigurationParams, TLMC_ApiVersion, TLMC_ButtonParams, TLMC_ConnectedProductInfo, TLMC_CurrentLoopParams, TLMC_DcPidParams, TLMC_DeviceInfo, TLMC_FirmwareVersion, TLMC_GeneralMoveParams, TLMC_HardwareInfo, TLMC_HomeParams, TLMC_IoConfigurationParams, TLMC_IoTriggerParams, TLMC_JogParams, TLMC_JoystickParams, TLMC_JoystickSettingsParams, TLMC_KcubeIoTriggerParams, TLMC_KcubeMmiParams, TLMC_KcubePositionTriggerParams, TLMC_LcdDisplayParams, TLMC_LcdMoveParams, TLMC_LimitSwitchParams, TLMC_MonitorOutputParams, TLMC_MotorOutputParams, TLMC_MoveAbsoluteParams, TLMC_MoveRelativeParams, TLMC_PZ_KpcIoSettingsParams, TLMC_PZ_KpcIoTriggerParams, TLMC_PZ_KpcMmiParams, TLMC_PZ_LnnxControlLoopParams, TLMC_PZ_LnnxNotchFilterParams, TLMC_PZ_MaxOutputVoltageParams, TLMC_PZ_NanoTrakCircleDiameterLookupTableData, TLMC_PZ_NanoTrakCircleHomePositionParams, TLMC_PZ_NanoTrakCircleParams, TLMC_PZ_NanoTrakEEPROMParams, TLMC_PZ_NanoTrakGainParams, TLMC_PZ_NanoTrakMode, TLMC_PZ_NanoTrakPhaseCompensationParams, TLMC_PZ_NanoTrakRangeParams, TLMC_PZ_NanoTrakStatus, TLMC_PZ_NanoTrakTnaIoSettings, TLMC_PZ_NanoTrakTrackThresholdParams, TLMC_PZ_OutputVoltageControlSourceParams, TLMC_PZ_OutputWaveformLoopTableSample, TLMC_PZ_OutputWaveformParams, TLMC_PZ_PositionLoopParams, TLMC_PZ_SlewRateParams, TLMC_PZ_StageInfoParams, TLMC_PZ_Status, TLMC_PositionLoopParams, TLMC_PotentiometerParams, TLMC_PowerParams, TLMC_ProfileModeParams, TLMC_RichResponse, TLMC_Setting, TLMC_StageAxisParams, TLMC_StatusItem, TLMC_StepperLoopParams, TLMC_StepperStatus, TLMC_TrackSettleParams, TLMC_TriggerParamsForDcBrushless, TLMC_TriggerParamsForStepper, TLMC_UniversalStatus, TLMC_Value, TLMC_VelocityParams

@runtime_checkable
class NativeFunctions(Protocol):

    def activate_calibration(self, handle: int): ...

    def add_user_message_to_log(self, user_message: str) -> None: ...

    def close(self, handle: int) -> None: ...

    def convert_from_device_units_to_physical(self, handle: int, scale_type: TLMC_ScaleType, device_value: int) -> tuple [float, TLMC_Unit]: ...

    def convert_from_physical_to_device(self, handle: int, scale_type: TLMC_ScaleType, unit: TLMC_Unit, physical_value: float) -> int: ...

    def create_simulation(self, description: Mapping[str, Any]) -> None: ...

    def deactivate_calibration(self, handle: int) -> None: ...

    def disconnect(self, handle: int) -> None: ...

    def set_actuator_type(self, handle: int, actuator_type: int) -> None: ...

    def get_adc_inputs(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_AdcInputs: ...

    def get_analog_monitor_configuration_params(self, handle: int, monitor_number: TLMC_AnalogMonitorNumber, max_wait_in_milliseconds: int) -> TLMC_AnalogMonitorConfigurationParams: ...

    def get_api_version(self) -> TLMC_ApiVersion: ...

    def get_aux_io_port_mode(self, handle: int, port_number: TLMC_AuxIoPortNumber, max_wait_in_milliseconds: int) -> TLMC_AuxIoPortMode: ...

    def get_aux_io_software_states(self, handle: int, max_wait_in_milliseconds: int) -> int: ...

    def get_button_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_ButtonParams: ...

    def get_calibration_state(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_CalibrationState: ...

    def get_bow_index(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_BowIndex: ...

    def get_connected_product(self, handle: int, max_length: int) -> str: ...

    def get_connected_product_info(self, handle: int) -> TLMC_ConnectedProductInfo: ...

    def get_connected_products_supported(self, handle: int) -> str: ...

    def get_current_loop_params(self, handle: int, loop_scenario: TLMC_CurrentLoopScenario, max_wait_in_milliseconds: int) -> TLMC_CurrentLoopParams: ...

    def get_dc_pid_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_DcPidParams: ...

    def get_device_info(self, handle: int) -> TLMC_DeviceInfo: ...

    def get_device_list_item_count(self) -> int: ...

    def get_device_list_items(self, source_start_index: int, number_of_items: int) -> List[TLMC_DeviceInfo]: ...

    def get_digital_input_states(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_DigitalInput: ...

    def get_digital_output_states(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_DigitalOutput: ...

    def get_enable_state(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_EnableState: ...
    
    def get_encoder_counter(self, handle: int, max_wait_in_milliseconds: int) -> int: ...

    def get_firmware_version_info(self, handle: int, max_wait_in_milliseconds: int) -> tuple [TLMC_FirmwareVersion, TLMC_FirmwareVersion]: ...

    def get_general_move_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_GeneralMoveParams: ...

    def get_hardware_info(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_HardwareInfo: ...

    def get_home_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_HomeParams: ...

    def get_io_configuration_number_of_ports_supported(self, handle: int) -> int: ...

    def get_io_configuration_params(self, handle: int, port_number: TLMC_IoPortNumber, max_wait_in_milliseconds: int) -> TLMC_IoConfigurationParams: ...

    def get_io_position_trigger_enable_state(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_IoPositionTriggerEnableState: ...

    def get_io_trigger_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_IoTriggerParams: ...

    def get_jog_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_JogParams: ...

    def get_joystick_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_JoystickParams: ...

    def get_joystick_settings_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_JoystickSettingsParams: ...

    def get_kcube_io_trigger_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_KcubeIoTriggerParams: ...

    def get_kcube_mmi_lock_state(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_KcubeMmiLockState: ...

    def get_kcube_mmi_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_KcubeMmiParams: ...

    def get_kcube_position_trigger_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_KcubePositionTriggerParams: ...

    def get_lcd_display_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_LcdDisplayParams: ...

    def get_lcd_move_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_LcdMoveParams: ...

    def get_limit_switch_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_LimitSwitchParams: ...

    def get_monitor_output_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_MonitorOutputParams: ...

    def get_motor_output_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_MotorOutputParams: ...

    def get_move_absolute_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_MoveAbsoluteParams: ...

    def get_move_relative_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_MoveRelativeParams: ...

    def get_position_counter(self, handle: int, max_wait_in_milliseconds: int) -> int: ...

    def get_position_loop_params(self, handle: int, position_loop_scenario: TLMC_PositionLoopScenario, max_wait_in_milliseconds: int) -> TLMC_PositionLoopParams: ...

    def get_potentiometer_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PotentiometerParams: ...

    def get_power_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PowerParams: ...

    def get_preferred_physical_unit(self, handle: int, scale_type: TLMC_ScaleType) -> TLMC_Unit: ...

    def get_profile_mode_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_ProfileModeParams: ...

    def get_rack_bay_occupied_state(self, handle: int, bay_number: TLMC_RackBayNumber, max_wait_in_milliseconds: int) -> TLMC_RackBayOccupiedState: ...

    def get_rich_response(self, handle: int) -> TLMC_RichResponse: ...

    def get_setting(self, handle: int, settings_name: str, max_wait_in_milliseconds: int) -> TLMC_Setting: ...

    def get_setting_count(self, handle: int) -> int: ...

    def get_settings(self, handle: int, source_start_index: int, number_of_items: int) -> List[TLMC_Setting]: ...

    def get_setting_discrete_values(self, handle: int, setting_name: str) -> str: ...

    def get_settings_as_string(self, handle: int, setting_string_format: TLMC_SettingStringFormat, include_read_only_items: bool) -> str: ...

    def get_status_item(self, handle: int, status_item_id: TLMC_StatusItemId) -> TLMC_StatusItem: ...

    def get_status_item_count(self, handle: int) -> int: ...

    def get_status_items(self, handle: int, start_index: int, number_of_items: int) -> List[TLMC_StatusItem]: ...

    def get_stage_axis_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_StageAxisParams: ...

    def get_stepper_loop_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_StepperLoopParams: ...

    def get_stepper_status(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_StepperStatus: ...

    def get_track_settle_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_TrackSettleParams: ...

    def get_trigger_params_for_dc_brushless(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_TriggerParamsForDcBrushless: ...

    def get_trigger_params_for_stepper(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_TriggerParamsForStepper: ...

    def get_universal_status(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_UniversalStatus: ...

    def get_universal_status_bits(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_UniversalStatusBit: ...

    def get_velocity_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_VelocityParams: ...

    def home(self, handle: int, max_wait_in_milliseconds: int) -> None: ...

    def identify(self, handle: int) -> None: ...

    def load_params(self, handle: int) -> None: ...

    def move(self, handle: int, mode: TLMC_MoveMode, param: int, max_wait_in_milliseconds: int) -> None: ...

    def move_absolute(self, handle: int, move_mode: TLMC_MoveMode, position: int, max_wait_in_milliseconds: int) -> None: ...

    def move_continuous(self, handle: int, direction: TLMC_MoveDirection, max_wait_in_milliseconds: int) -> None: ...

    def move_jog(self, handle: int, direction: TLMC_MoveDirection, max_wait_in_milliseconds: int) -> None: ...

    def move_relative(self, handle: int, move_mode: TLMC_MoveMode, step_size: int, max_wait_in_milliseconds: int) -> None: ...

    def open(self, device: str, transport_type: str, operating_mode: TLMC_OperatingMode) -> int: ...

    def persist_params(self, handle: int, parameter_group_id: TLMC_ParameterGroupId) -> None: ...

    def pz_get_kpc_io_settings_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_KpcIoSettingsParams: ...

    def pz_get_kpc_io_trigger_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_KpcIoTriggerParams: ...

    def pz_get_kpc_mmi_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_KpcMmiParams: ...

    def pz_get_lnnx_control_loop_params(self, max_wait_in_milliseconds: int) -> TLMC_PZ_LnnxControlLoopParams: ...

    def pz_get_lnnx_notch_filter_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_LnnxNotchFilterParams: ...

    def pz_get_max_output_voltage_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_MaxOutputVoltageParams: ...

    def pz_get_max_travel(self, handle: int, max_wait_in_milliseconds: int) -> int: ...

    def pz_get_nano_trak_circle_diameter_lookup_table_data(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakCircleDiameterLookupTableData: ...

    def pz_get_nano_trak_circle_home_position(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakCircleHomePositionParams: ...

    def pz_get_nano_trak_circle_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakCircleParams: ...

    def pz_get_nano_trak_gain_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakGainParams: ...

    def pz_get_nano_trak_mode(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakMode: ...

    def pz_get_nano_trak_phase_compensation_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakPhaseCompensationParams: ...

    def pz_get_nano_trak_range_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakRangeParams: ...

    def pz_get_nano_trak_status(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakStatus: ...

    def pz_get_nano_trak_tna_io_settings(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakTnaIoSettings: ...

    def pz_get_nano_trak_track_threshold(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_NanoTrakTrackThresholdParams: ...

    def pz_get_output_voltage(self, handle: int, max_wait_in_milliseconds: int) -> int: ...

    def pz_get_output_voltage_control_source_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_OutputVoltageControlSourceParams: ...

    def pz_get_output_waveform_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_OutputWaveformParams: ...

    def pz_get_position(self, handle: int, max_wait_in_milliseconds: int) -> int: ...

    def pz_get_position_control_mode(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_PositionControlMode: ...

    def pz_get_position_loop_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_PositionLoopParams: ...

    def pz_get_slew_rate_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_SlewRateParams: ...

    def pz_get_stage_info_params(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_StageInfoParams: ...

    def pz_get_status(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_Status: ...

    def pz_get_status_bits(self, handle: int, max_wait_in_milliseconds: int) -> TLMC_PZ_StatusBit: ...

    def pz_nano_trak_circle_to_home_position(self, handle: int) -> None: ...

    def pz_nano_trak_tia_self_calibrate(self, handle: int) -> None: ...

    def pz_set_kpc_io_settings_params(self, handle: int, params: TLMC_PZ_KpcIoSettingsParams) -> None: ...

    def pz_set_kpc_io_trigger_params(self, handle: int, params: TLMC_PZ_KpcIoTriggerParams) -> None: ...

    def pz_set_kpc_mmi_params(self, handle: int, params: TLMC_PZ_KpcMmiParams) -> None: ...

    def pz_set_lnnx_control_loop_params(self, handle: int, params: TLMC_PZ_LnnxControlLoopParams) -> None: ...

    def pz_set_lnnx_notch_filter_params(self, handle: int, params: TLMC_PZ_LnnxNotchFilterParams) -> None: ...

    def pz_set_max_output_voltage(self, handle: int, max_output_voltage: int) -> None: ...

    def pz_set_max_travel(self, handle: int, max_travel: int) -> None: ...

    def pz_set_nano_trak_circle_diameter(self, handle: int, nano_trak_circle_diameter: int) -> None: ...

    def pz_set_nano_trak_circle_diameter_lookup_table_data(self, handle: int, params: TLMC_PZ_NanoTrakCircleDiameterLookupTableData) -> None: ...

    def pz_set_nano_trak_circle_home_position(self, handle: int, params: TLMC_PZ_NanoTrakCircleHomePositionParams) -> None: ...

    def pz_set_nano_trak_circle_params(self, handle: int, params: TLMC_PZ_NanoTrakCircleParams) -> None: ...

    def pz_set_nano_trak_eeprom_params(self, handle: int, params: TLMC_PZ_NanoTrakEEPROMParams) -> None: ...

    def pz_set_nano_trak_gain_params(self, handle: int, params: TLMC_PZ_NanoTrakGainParams) -> None: ...

    def pz_set_nano_trak_mode(self, handle: int, set_mode: TLMC_PZ_SetNanoTrakModeType) -> None: ...

    def pz_set_nano_trak_phase_compensation_params(self, handle: int, params: TLMC_PZ_NanoTrakPhaseCompensationParams) -> None: ...

    def pz_set_nano_trak_range_params(self, handle: int, params: TLMC_PZ_NanoTrakRangeParams) -> None: ...

    def pz_set_nano_trak_tna_io_settings(self, handle: int, params: TLMC_PZ_NanoTrakTnaIoSettings) -> None: ...

    def pz_set_nano_trak_track_threshold(self, handle: int, params: TLMC_PZ_NanoTrakTrackThresholdParams) -> None: ...

    def pz_set_output_voltage(self, handle: int, new_output_voltage: int) -> None: ...

    def pz_set_output_voltage_control_source_params(self, handle: int, params: TLMC_PZ_OutputVoltageControlSourceParams) -> None: ...

    def pz_set_output_waveform_loop_table_sample(self, handle: int, params: TLMC_PZ_OutputWaveformLoopTableSample) -> None: ...

    def pz_set_output_waveform_params(self, handle: int, params: TLMC_PZ_OutputWaveformParams) -> None: ...

    def pz_set_position(self, handle: int, new_position: int) -> None: ...

    def pz_set_position_control_mode(self, handle: int, control_mode: TLMC_PZ_PositionControlMode, max_wait_in_milliseconds: int) -> None: ...

    def pz_set_position_loop_params(self, handle: int, params: TLMC_PZ_PositionLoopParams) -> None: ...

    def pz_set_slew_rate_params(self, handle: int, params: TLMC_PZ_SlewRateParams) -> None: ...

    def pz_set_zero(self, handle: int, max_wait_in_milliseconds: int) -> None: ...

    def pz_start_output_waveform(self, handle: int) -> None: ...

    def pz_stop_output_waveform(self, handle: int) -> None: ...

    def rack_identify(self, handle: int, channel: int) -> None: ...

    def request_status(self, handle: int, max_wait_in_milliseconds: int) -> None: ...

    def remove_simulation(self, description: str) -> None: ...

    def restore_factory_defaults(self, handle: int) -> None: ...

    def send_no_flash_programming(self, handle: int) -> None: ...

    def send_yes_flash_programming(self, handle: int) -> None: ...

    def set_analog_monitor_configuration_params(self, handle: int, monitor_number: TLMC_AnalogMonitorNumber, params: TLMC_AnalogMonitorConfigurationParams) -> None: ...

    def set_aux_io_port_mode(self, handle: int, port_number: TLMC_AuxIoPortNumber, port_mode: TLMC_AuxIoPortMode) -> None: ...

    def set_aux_io_software_states(self, handle: int, software_states: int) -> None: ...

    def set_bow_index(self, handle: int, bow_index: TLMC_BowIndex) -> None: ...

    def set_button_params(self, handle: int, params: TLMC_ButtonParams) -> None: ...

    def set_connected_product(self, handle: int, product_name: str) -> None: ...

    def set_connected_product_info(self, handle: int, params: TLMC_ConnectedProductInfo) -> None: ...

    def set_current_loop_params(self, handle: int, scenario: TLMC_CurrentLoopScenario, params: TLMC_CurrentLoopParams) -> None: ...

    def set_dc_pid_params(self, handle: int, params: TLMC_DcPidParams) -> None: ...

    def set_digital_output_states(self, handle: int, output_state: TLMC_DigitalOutput) -> None: ...

    def set_enable_state(self, handle: int, enable_state: TLMC_EnableState) -> None: ...

    def set_encoder_counter(self, handle: int, encoder_counter: int) -> None: ...

    def set_end_of_move_messages_mode(self, handle: int, messages_mode: TLMC_EndOfMoveMessagesMode) -> None: ...

    def set_general_move_params(self, handle: int, params: TLMC_GeneralMoveParams) -> None: ...

    def set_home_params(self, handle: int, params: TLMC_HomeParams) -> None: ...

    def set_io_configuration_params(self, handle: int, port_number: TLMC_IoPortNumber, params: TLMC_IoConfigurationParams) -> None: ...

    def set_io_position_trigger_enable_state(self, handle: int, enable_state: TLMC_IoPositionTriggerEnableState, max_wait_in_milliseconds: int) -> None: ...

    def set_io_trigger_params(self, handle: int, params: TLMC_IoTriggerParams) -> None: ...

    def set_joystick_params(self, handle: int, params: TLMC_JoystickParams) -> None: ...

    def set_joystick_settings_params(self, handle: int, params: TLMC_JoystickSettingsParams) -> None: ...

    def set_kcube_io_trigger_params(self, handle: int, params: TLMC_KcubeIoTriggerParams) -> None: ...

    def set_kcube_mmi_lock_state(self, handle: int, lock_state: TLMC_KcubeMmiLockState) -> None: ...

    def set_kcube_mmi_params(self, handle: int, params: TLMC_KcubeMmiParams) -> None: ...

    def set_kcube_position_trigger_params(self, handle: int, params: TLMC_KcubePositionTriggerParams) -> None: ...

    def set_lcd_display_params(self, handle: int, params: TLMC_LcdDisplayParams) -> None: ...

    def set_lcd_move_params(self, handle: int, params: TLMC_LcdMoveParams) -> None: ...

    def set_limit_switch_params(self, handle: int, params: TLMC_LimitSwitchParams) -> None: ...

    def set_motor_output_params(self, handle: int, params: TLMC_MotorOutputParams) -> None: ...

    def set_move_absolute_params(self, handle: int, params: TLMC_MoveAbsoluteParams) -> None: ...

    def set_jog_params(self, handle: int, params: TLMC_JogParams) -> None: ...

    def set_monitor_output_params(self, handle: int, params: TLMC_MonitorOutputParams) -> None: ...

    def set_move_relative_params(self, handle: int, params: TLMC_MoveRelativeParams) -> None: ...

    def set_position_counter(self, handle: int, position_counter: int) -> None: ...

    def set_position_loop_params(self, handle: int, scenario: TLMC_PositionLoopScenario, params: TLMC_PositionLoopParams) -> None: ...

    def set_potentiometer_params(self, handle: int, params: TLMC_PotentiometerParams) -> None: ...

    def set_power_params(self, handle: int, params: TLMC_PowerParams) -> None: ...

    def set_profile_mode_params(self, handle: int, params: TLMC_ProfileModeParams) -> None: ...

    def set_setting(self, handle: int, setting_name: str, value: TLMC_Value) -> None: ...

    def set_settings_from_string(self, handle: int, settings: str) -> None: ...

    def set_stage_axis_params(self, handle: int, params: TLMC_StageAxisParams) -> None: ...

    def set_status_mode(self, handle: int, operating_mode: TLMC_OperatingMode) -> None: ...

    def set_stepper_loop_params(self, handle: int, params: TLMC_StepperLoopParams) -> None: ...

    def set_track_settle_params(self, handle: int, params: TLMC_TrackSettleParams) -> None: ...

    def set_trigger_params_for_dc_brushless(self, handle: int, params: TLMC_TriggerParamsForDcBrushless) -> None: ...

    def set_trigger_params_for_stepper(self, handle: int, params: TLMC_TriggerParamsForStepper) -> None: ...

    def set_velocity_params(self, handle: int, params: TLMC_VelocityParams) -> None: ...

    def shutdown(self) -> None: ...

    def startup(self, settings_file_name: Optional[str]) -> None: ...

    def stop(self, handle: int, stop_mode: TLMC_StopMode, max_wait_in_milliseconds: int) -> None: ...